### PR TITLE
GPII-4491: Update all dependencies (and convert to promisory mkdirp).

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-4491](https://issues.gpii.net/browse/GPII-4491) for details.

### CODE REVIEW

**Comment by amb26** [comment]
Looks like a real failure:
````
07:32:54.573:  jq: Test concluded - Module "File change 'watcher' tests." Test name "We should be able to detect a file that has been deleted.": 2/3 passed - FAIL
07:32:54.584:  Creating directory 'C:\Users\vagrant\AppData\Local\Temp\watcher-test-dir-7fkefz2s-4620'...
07:32:54.585:  Temporary content cleanup complete...
````

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
VM creation failure: ok to test

**Comment by amb26** [comment]
Aha - gotcha!
````
==> windows10: 04:23:35.021:  FATAL ERROR: Uncaught exception: EPERM: operation not permitted, scandir 'C:\Users\vagrant\AppData\Local\Temp\watcher-test-dir-6ot5wikl-4544'
==> windows10: Error: EPERM: operation not permitted, scandir 'C:\Users\vagrant\AppData\Local\Temp\watcher-test-dir-6ot5wikl-4544'
==> windows10: 04:23:35.023:  jq: FAIL: Module "File change 'watcher' tests." Test name "We should be able to detect a file that has been changed." - Message: Unexpected failure in test case (see following log for more details): EPERM: operation not permitted, scandir 'C:\Users\vagrant\AppData\Local\Temp\watcher-test-dir-6ot5wikl-4544'
==> windows10: 04:23:35.023:  jq: Source:     at kettle.test.handleUncaughtException (V:\node_modules\kettle\lib\test\KettleTestUtils.js:31:15)
==> windows10:     at Object.fire (V:\node_modules\infusion\src\framework\core\js\Fluid.js:1721:40)
==> windows10:     at process.onUncaughtException (V:\node_modules\infusion\src\module\fluid.js:237:31)
==> windows10:     at process.emit (events.js:310:20)
==> windows10:     at processEmit [as emit] (V:\node_modules\signal-exit\index.js:161:32)
==> windows10:     at process._fatalException (internal/process/execution.js:164:25)
==> windows10: 04:23:35.028:  Template change watcher ready...
==> windows10: 04:23:35.029:  Adding new file 'C:\Users\vagrant\AppData\Local\Temp\watcher-test-dir-6ot5wikl-4570\changingFile.txt'.
==> windows10: 04:23:35.061:  jq: Test concluded - Module "File change 'watcher' tests." Test name "We should be able to detect a file that has been changed.": 2/3 passed - FAIL
````

**Comment by the-t-in-rtf** [comment]
Thanks for taking the time to chase that one down, I had seen it intermittently.  Previously I was removing watched content immediately before closing the watcher, which is the wrong way round.  I suspect the errors were the watcher caught in mid-scan when the directory was removed.  I have switched this order, we can go through a couple of passes here.

**Comment by the-t-in-rtf** [comment]
Early provisioning failure on the latest build, it may limp through the rest or not.  Will test repeatedly locally while I wait.

**Comment by the-t-in-rtf** [comment]
The actual tests passed, but the provisioning failed before grunt was installed, so that stage and the linting stage failed.

I ran the tests in a VM five times in a row without encountering further EPERM errors, but it's OK to test again, hopefully we can get a successful CI build to close out the conversation.

**Comment by amb26** [comment]
ok to test

**Comment by the-t-in-rtf** [comment]
Cheers, published the release on npm and github and updated the forward-facing version.

**Pull request merged**
