### PR TITLE
GPII-1180:  Improved dispatcher root handling to use index page....

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-1180](https://issues.gpii.net/browse/GPII-1180) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
Most of these commits are related to GPII-1175, only the last is relevant to this particular issue.

**Comment by amb26** [comment]
The cause of the failure is pretty clear - you have arranged to instantiate a component which is a rendererHolder which has a subcomponent reading: 
    rendererHolder: "{rendererHolder}.renderer"
As Alice said, "That'll never be done". I've issued a framework pull which will give a clearer diagnostic: https://github.com/fluid-project/infusion/pull/613 - but you will still have to reorganise your grades so that the only source of the injected component is at the top of the tree.

**Comment by the-t-in-rtf** [comment]
@amb26 We should chat again, as a key point is to make nesting possible, if this approach will only work with a single "top of the tree", then it's not good enough.  How can people ever deprive an existing component of its "top of the tree" status if they want to use it as a "branch" in the future?  If we have a base version of each complex component and then another that is wired to distribute a renderer, then it's possible to safely reuse components, but it seems difficult to communicate to others how to safely compose their own components or even to use ours.

**Comment by the-t-in-rtf** [comment]
@amb26, I have largely implemented my workaround, but could use some help with the lifecycle when you're around.

**Comment by the-t-in-rtf** [comment]
I believe GPII-1125 addresses the last comment, and that there is nothing that remains to be done before this can be merged.

**Comment by the-t-in-rtf** [comment]
All changes have been merged into GPII-1222, which is under final review before merging: https://github.com/GPII/gpii-handlebars/pull/9

**Pull request closed without merging**
