### PR TITLE
GH-37: Migrate to fluid-lint-all (resolves #37).

### LINKED ISSUE #37: Migrate to fluid-lint-all.
Migrate to fluid-lint-all and npx.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
Move from Grunt/fluid-grunt-lint-all to fluid-lint-all.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
I think one of the other dependency updates broke things.  I'll confirm and flag any problems as separate follow up issues.

**Comment by the-t-in-rtf** [comment]
I made a few passes at it, the tests fail unless I downgrade both `infusion` and `chokidar` (breaks node tests).  I will file a ticket for the chokidar work for later, as that's lower priority.

The `infusion` issues are more serious.  The linting fails with circular dependency issues if I use the version we used previously in this package (`3.0.0-dev.20200525T143422Z.f7f6aab.FLUID-6148`).  If I update to `3.0.0-dev.20201113T153152Z.32176dcbe.FLUID-6145`, the browser tests hang.

I'll try debugging the Testem tests to see if I can figure out what's going on.

**Comment by the-t-in-rtf** [comment]
@amb26, I have pared this down just to run the failing test, which is one that is a nest of resource loading and event chaining.  Based on careful experimentation, I have confirmed that I can only ever get one of the two sub-components in this test to finish initialising:

https://github.com/the-t-in-rtf/fluid-handlebars/blob/7ac38aee3d08caa8aff51c9164c70b9371997eb3/tests/browser-fixtures/js/tests-templateAware-serverResourceAware.js#L88

By default on my machine, only the log statement for the "contained" component is fired.  If I comment out the "contained" subcomponent definition, the statement for the "main" component is logged.  This matches my experience in the debugger, when both are active, the "main" component's render invoker is not called.

I could use help figuring out why this worked before (in `3.0.0-dev.20200525T143422Z.f7f6aab.FLUID-6148`) but does not work now (in `3.0.0-dev.20201113T153152Z.32176dcbe.FLUID-6145`).

**Comment by the-t-in-rtf** [comment]
I can't reproduce the `chokidar` issues with a newer infusion, I'll wait to update, test, and potentially file a bug report once we address the primary issue.

**Comment by the-t-in-rtf** [comment]
As it's been a while, here's a reminder of steps to see the behaviour:

1. Check out the branch, blow away the node_modules and install.
2. From the root of the repo, run `node node_modules/testem/testem.js --file tests/testem.js`
3. Open the URL returned by Testem in a browser.
4. Check the console output.  The tests cannot continue until both components indicate that their markup has been rendered, and only one of the required events is fired / logged.

**Comment by amb26** [comment]
Looks like a pretty clear framework bug in all recent versions of the framework - though this trace, we manage to fire onResourcesLoaded before the framework can register the createOnEvent listener: 
````
bindDeferred instantiation for main of parent component { typeName: "fluid.tests.templateAware.testEnvironment id: 7oh44guo-77" gradeNames: ["fluid.test.testEnvironment","fluid.tests.templateAware.testEnvironment"]} at path testEnvironment-7oh44guo-77 for event {that}.events.createFixtures
testem.js:967 bindDeferred instantiation for contained of parent component { typeName: "fluid.tests.templateAware.testEnvironment id: 7oh44guo-77" gradeNames: ["fluid.test.testEnvironment","fluid.tests.templateAware.testEnvironment"]} at path testEnvironment-7oh44guo-77 for event {that}.events.createFixtures
testem.js:967 firing onResourcesLoaded for component { typeName: "fluid.tests.templateAware.serverResourceAware id: 7oh44guo-124" gradeNames: ["fluid.resourceLoader","fluid.handlebars.serverResourceAware","fluid.binder","fluid.binder.bindOnDomChange","fluid.baseViewComponent","fluid.handlebars.templateAware","fluid.handlebars.templateAware.serverResourceAware","fluid.tests.handlebars.templateAware.serverResourceAware","fluid.tests.templateAware.serverResourceAware"]} at path testEnvironment-7oh44guo-77.main
testem.js:967 Added bindDeferred listener to event {fluid.handlebars.serverResourceAware}.events.onResourcesLoaded of component { typeName: "fluid.tests.templateAware.contained id: 7oh44guo-125" gradeNames: ["fluid.resourceLoader","fluid.handlebars.serverResourceAware","fluid.binder","fluid.binder.bindOnDomChange","fluid.baseViewComponent","fluid.handlebars.templateAware","fluid.handlebars.templateAware.serverResourceAware","fluid.tests.handlebars.templateAware.serverResourceAware","fluid.tests.templateAware.serverResourceAware","fluid.tests.templateAware.contained"]} at path testEnvironment-7oh44guo-77.contained:  fluid.event.firer
testem.js:967 Added bindDeferred listener to event {fluid.handlebars.serverResourceAware}.events.onResourcesLoaded of component { typeName: "fluid.tests.templateAware.serverResourceAware id: 7oh44guo-124" gradeNames: ["fluid.resourceLoader","fluid.handlebars.serverResourceAware","fluid.binder","fluid.binder.bindOnDomChange","fluid.baseViewComponent","fluid.handlebars.templateAware","fluid.handlebars.templateAware.serverResourceAware","fluid.tests.handlebars.templateAware.serverResourceAware","fluid.tests.templateAware.serverResourceAware"]} at path testEnvironment-7oh44guo-77.main:  fluid.event.fireraddListener: ƒ (listener, namespace, priority, softNamespace, listenerId)byId: {7oh44guo-242: {…}, 7oh44guo-120: {…}}destroy: ƒ ()eventId: "7oh44guo-134"fire: ƒ ()listeners: 7oh44guo-242: [{…}]fluid-componentConstruction: [{…}]__proto__: Objectname: "onResourcesLoaded of component { typeName: "fluid.tests.templateAware.serverResourceAware id: 7oh44guo-124" gradeNames: ["fluid.resourceLoader","fluid.handlebars.serverResourceAware","fluid.binder","fluid.binder.bindOnDomChange","fluid.baseViewComponent","fluid.handlebars.templateAware","fluid.handlebars.templateAware.serverResourceAware","fluid.tests.handlebars.templateAware.serverResourceAware","fluid.tests.templateAware.serverResourceAware"]} at path testEnvironment-7oh44guo-77.main"onDestroy: nullownerId: "7oh44guo-124"removeListener: ƒ (listener)sortedListeners: (2) [{…}, {…}]typeName: "fluid.event.firer"__proto__: Object
testem.js:967 firing onResourcesLoaded for component { typeName: "fluid.tests.templateAware.contained id: 7oh44guo-125" gradeNames: ["fluid.resourceLoader","fluid.handlebars.serverResourceAware","fluid.binder","fluid.binder.bindOnDomChange","fluid.baseViewComponent","fluid.handlebars.templateAware","fluid.handlebars.templateAware.serverResourceAware","fluid.tests.handlebars.templateAware.serverResourceAware","fluid.tests.templateAware.serverResourceAware","fluid.tests.templateAware.contained"]} at path testEnvironment-7oh44guo-77.contained
testem.js:967 bindDeferred instantiation for renderer of parent component { typeName: "fluid.tests.templateAware.contained id: 7oh44guo-125" gradeNames: ["fluid.resourceLoader","fluid.handlebars.serverResourceAware","fluid.binder","fluid.binder.bindOnDomChange","fluid.baseViewComponent","fluid.handlebars.templateAware","fluid.handlebars.templateAware.serverResourceAware","fluid.tests.handlebars.templateAware.serverResourceAware","fluid.tests.templateAware.serverResourceAware","fluid.tests.templateAware.contained"]} at path testEnvironment-7oh44guo-77.contained for event {fluid.handlebars.serverResourceAware}.events.onResourcesLoaded
testem.js:967 containedRendered event triggered.
````

This bug filed as https://issues.fluidproject.org/browse/FLUID-6588

**Comment by the-t-in-rtf** [comment]
Just to summarise, this pull is blocked until we either have a workaround or updated version of Infusion. The problems here are only tangentially related to fluid-lint-all, by virtue of having to upgrade to a new enough variant of FLUID-6145 to avoid spurious circular dependency warnings when running fluid-lint-all.  I'd propose pausing this review until a framework fix is available and moving on to other packages.  I will test all other fluid-X libraries with FLUID-6145 as well just to confirm whether they are similarly affected.

**Comment by amb26** [comment]
I've rolled release 3.0.0-dev.20210114T211758Z.d345ecd74.FLUID-6145 which fixes FLUID-6588 and verified that the tests in this branch pass with it

**Comment by the-t-in-rtf** [comment]
Self-merging dependency updates per discussion with Antranig.

**Pull request merged**
