### PR TITLE
GPII-4480: Update to work with newer 'mainline' infusion.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-4480](https://issues.gpii.net/browse/GPII-4480) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
The browser tests should hang because of an error with resource loading.  To see the mangled URL I mention in the ticket, run `node node_modules/testem/testem.js --file tests/testem.js`, then connect your browser and open the debugger.  You'll see an error about not being able to find a resource, but if you look at the network tab in the debugger, you'll see the badly mangled resource URL.

cc: @amb26

**Comment by amb26** [comment]
Thanks for the report, I'll take a look - I hadn't thought there had been any important changes in this area in mainline Infusion, are you by any chance able to lay your hands on a mainline revision that this ever worked with?

**Comment by the-t-in-rtf** [comment]
The last mainline I used was `3.0.0-dev.20190328T144119Z.ec44dbfab`.  I get a different test failure related to prioritisation if I use that with this branch.

**Comment by amb26** [comment]
The problem here is the rather broken impl of fluid.resourceLoader.resolveResources - https://github.com/fluid-project/infusion/blob/master/src/framework/core/js/ResourceLoader.js#L58 note that this old implementation did not accept full resource structures on the RHS but expected that they just consisted of URLs. Your code has probably not worked with mainline releases since your GPII-4100 update of https://github.com/GPII/gpii-handlebars/commit/45989f6ea808caf37d849628202e2499c9d82261 

Since fluid.resourceLoader.resolveResources does not exist at all on any new framework, I think the best option if you want compatibility with mainline releases is for you to monkey-patch it so that it accepts both kinds of RHS. However, it may be best for us to just move to FLUID-6148 branches at a minimum - do try with 3.0.0-dev.20200512T100752Z.0d704c4.FLUID-6148 to see if it is free of horrors

**Comment by the-t-in-rtf** [comment]
I get a different error with `3.0.0-dev.20200512T100752Z.0d704c4.FLUID-6148`.  The resource loading does seem to work.  I'll see if it's a goof on my part and commit either way shortly.

**Comment by the-t-in-rtf** [comment]
As discussed in other pulls and chats, @amb26 asked me to try a newer variant of the FLUID-6145 branch.  It fails with the same issue as FLUID-6148, namely the "messages" resource is stuffed into both the "messages" and "templates" model variable.   Hilariously, this new bug has the same error message and testem hang behaviour as the previous issue, I temporarily added console logging to illustrate the new issue better.

**Comment by amb26** [comment]
This was filed as https://issues.fluidproject.org/browse/FLUID-6503 and I have now rolled paired versions of the FLUID-6148 and FLUID-6145 branches both of which incorporate the fix - 3.0.0-dev.20200525T143422Z.f7f6aab.FLUID-6148 and 3.0.0-dev.20200525T161532Z.fc4d4b3.FLUID-6145 - this branch should now work with either

**Comment by the-t-in-rtf** [comment]
EPERM error cleaning up after the test run:

```
==> windows10: Error: EPERM: operation not permitted, scandir 'C:\Users\vagrant\AppData\Local\Temp\watcher-test-dir-32ejf1bj-1317'
==> windows10: 00:58:38.261:  jq: FAIL: Module "Tests for inlining of templates..." Test name "Confirm that template content is inlined..." - Message: Unexpected failure in test case (see following log for more details): EPERM: operation not permitted, scandir 'C:\Users\vagrant\AppData\Local\Temp\watcher-test-dir-32ejf1bj-1317'
==> windows10: 00:58:38.261:  jq: Source:     at kettle.test.handleUncaughtException (V:\node_modules\kettle\lib\test\KettleTestUtils.js:31:15)
==> windows10:     at Object.fire (V:\node_modules\infusion\src\framework\core\js\Fluid.js:1721:40)
==> windows10:     at process.onUncaughtException (V:\node_modules\infusion\src\module\fluid.js:237:31)
==> windows10:     at process.emit (events.js:310:20)
==> windows10:     at processEmit [as emit] (V:\node_modules\signal-exit\index.js:161:32)
==> windows10:     at process._fatalException (internal/process/execution.js:164:25)
```

Verifying in a local machine, might be a timing issue or a new windows-specific bug.

**Comment by the-t-in-rtf** [comment]
I can reproduce the error, and unfortunately it's an error bleeding over from the watcher tests into another non-IoC test.  I'll convert the watcher tests to an IoC test for starters.

**Comment by the-t-in-rtf** [comment]
Didn't even manage to get past the early stages of provisioning the VM, timed out after 45 minutes.  Ok to test.

**Comment by the-t-in-rtf** [comment]
Thanks, it definitely passes locally and in a VM as well.

**Pull request merged**
